# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zvJZk9Hol3qrvQCVyZqb-xU14Vpy0tCe
"""

import streamlit as st
import numpy as np
import pandas as pd
import cv2
from tensorflow.keras.models import load_model
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
import io
import tempfile

model = load_model("isl_recognition_model.keras", compile=False)

labels = ['Bad','Car','Cat','Cell_Phone','Cold','Expensive','Father','Friend','Happy','Hello','Hospital','How_Are_You','Money',
 'Monsoon','Mother','Pocket','Red','Thankyou','Time','Today']

base_options_hand = python.BaseOptions(model_asset_path='hand_landmarker.task')
options_hand = vision.HandLandmarkerOptions(base_options=base_options_hand, num_hands=2, running_mode=vision.RunningMode.IMAGE)
hand_detector = vision.HandLandmarker.create_from_options(options_hand)

base_options_face = python.BaseOptions(model_asset_path='face_landmarker.task')
options_face = vision.FaceLandmarkerOptions(base_options=base_options_face, num_faces=1, running_mode=vision.RunningMode.IMAGE)
face_detector = vision.FaceLandmarker.create_from_options(options_face)

base_options_pose = python.BaseOptions(model_asset_path='pose_landmarker_lite.task')
options_pose = vision.PoseLandmarkerOptions(base_options=base_options_pose, running_mode=vision.RunningMode.IMAGE)
pose_detector = vision.PoseLandmarker.create_from_options(options_pose)

def extract_landmarks(mp_image):
    hand_result = hand_detector.detect(mp_image)
    face_result = face_detector.detect(mp_image)
    pose_result = pose_detector.detect(mp_image)

    lhand = [[0,0,0]]*21
    rhand = [[0,0,0]]*21
    if hand_result.hand_landmarks:
        for idx, hand_landmarks in enumerate(hand_result.hand_landmarks):
            handedness_label = hand_result.handedness[idx][0].category_name
            landmarks_list = [[lm.x, lm.y, lm.z] for lm in hand_landmarks]

            if handedness_label == 'Left':
                lhand = landmarks_list
            elif handedness_label == 'Right':
                rhand = landmarks_list


    if face_result.face_landmarks:
        face = [[lm.x, lm.y, lm.z] for lm in face_result.face_landmarks[0]]
    else:
        face = [[0,0,0]]*478


    if pose_result.pose_landmarks:
        pose = [[lm.x, lm.y, lm.z] for lm in pose_result.pose_landmarks[0]]
    else:
        pose = [[0,0,0]]*33

    landmark = np.array(lhand + rhand + face + pose).flatten()
    return landmark

st.set_page_config(page_title="ISL Word Recognition", layout="wide")
st.title("Indian Sign Language Word Recognition")

video = st.file_uploader(
    "Upload Sign Language Video",
    type=["mp4", "avi", "mov"]
)

if video:
    st.video(video)
    st.success("Video uploaded successfully!")

    tfile = tempfile.NamedTemporaryFile(delete=False)
    tfile.write(video.read())

    cap = cv2.VideoCapture(tfile.name)
    sequence = []
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        img_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=img_rgb)

        keypoints = extract_landmarks(mp_image)
        sequence.append(keypoints)

    cap.release()
    if len(sequence) >= 75:
        sequence = sequence[-75:]
    else:
        padding = [np.zeros(1659)] * (75 - len(sequence))
        sequence.extend(padding)
        sequence = sequence[:75]
    result = np.expand_dims(sequence, axis=0)
    predictions = model.predict(result, verbose=0)[0]

    predicted_index = np.argmax(predictions)
    probability = predictions[predicted_index]

    if probability > 0.30:
        text = f"Word: {labels[predicted_index]} ({probability*100:.2f}%)"
        st.text(text)
    else:
        st.text("Word not recognized")
st.subheader("Supported Vocabulary")
st.text(f"Total Classes: {len(labels)}")
st.table(labels)

report = """   precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       1.00      1.00      1.00         3
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00         1
           4       0.57      1.00      0.73         4
           5       1.00      1.00      1.00         1
           6       1.00      1.00      1.00         1
           7       0.50      0.33      0.40         3
           8       1.00      1.00      1.00         3
           9       0.50      0.33      0.40         3
          10       0.75      1.00      0.86         3
          11       1.00      0.83      0.91         6
          12       0.33      0.33      0.33         3
          13       1.00      1.00      1.00         1
          14       0.75      1.00      0.86         3
          15       1.00      0.33      0.50         3
          16       0.33      0.50      0.40         2
          17       1.00      1.00      1.00         2
          18       1.00      0.50      0.67         4
          19       0.33      0.33      0.33         3

"""
lines = report.split('\n')
cleaned_report = "\n".join([line.strip() for line in lines if line.strip()])

df = pd.read_csv(io.StringIO(cleaned_report), sep=r'\s+', engine='python')
st.subheader("Model Performance")
st.metric("Accuracy", "74.07%")
st.dataframe(df)

st.subheader("Data Representation")
data = {
    'Class': labels,
    'f1-score': [0.67,1.00,1.00,1.00,0.73,1.00,1.00,0.40,1.00,0.40,0.86,0.91,0.33,1.00,0.86,0.50,0.40,1.00,0.67,0.33],

    'Precision score': [0.50,1.00,1.00,1.00,0.57,1.00,1.00,0.50,1.00,0.50,0.75,1.00,0.33,1.00,0.75,1.00,0.33,1.00,1.00,0.33],

    'Recall score': [1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.33,1.00,0.33,1.00,0.83,0.33,1.00,1.00,0.33,0.50,1.00,0.50,0.33]

}
data = pd.DataFrame(data)
metric = ['Precision','Recall','f1-score']
metric = st.radio("Select Metric",metric)
if metric == 'Precision':
    st.bar_chart(data, x='Class', y='Precision score', color="#1F9AFF")
elif metric == 'Recall':
    st.bar_chart(data, x='Class', y='Recall score', color="#FF911F")
elif metric == 'f1-score':
    st.bar_chart(data, x='Class', y='f1-score', color="#960978")